# Generated by Django 3.2.9 on 2021-12-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='media/car')),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('car_text', models.TextField(blank=True, max_length=300, null=True)),
                ('car_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_style', models.CharField(blank=True, max_length=100, null=True)),
                ('car_excolor', models.CharField(blank=True, max_length=100, null=True)),
                ('car_intcolor', models.CharField(blank=True, max_length=100, null=True)),
                ('car_mpg', models.IntegerField(blank=True, null=True)),
                ('car_engine', models.CharField(blank=True, max_length=100, null=True)),
                ('car_drivetype', models.CharField(blank=True, choices=[('4WD', '4WD'), ('2WD', '2WD')], default='4WD', max_length=4, null=True)),
                ('car_fueltype', models.CharField(blank=True, choices=[('DIESEL', 'DIESEL'), ('GASOLINE', 'GASOLINE'), ('GAS', 'GAS')], default='GASOLINE', max_length=10, null=True)),
                ('car_transmiossion', models.CharField(blank=True, choices=[('MANUAL', 'MANUAL'), ('AUTOMATIK', 'AUTOMATIK')], default='MANUAL', max_length=10, null=True)),
                ('car_ns', models.CharField(blank=True, max_length=100, null=True)),
                ('car_dpp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_fjdssp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_rrstp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_wcp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_cp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_bwlp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_edp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_lccvp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_sp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_8s', models.CharField(blank=True, max_length=100, null=True)),
                ('car_dvd', models.CharField(blank=True, max_length=100, null=True)),
                ('car_dp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_fccvp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_pcapp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_vcp', models.CharField(blank=True, max_length=100, null=True)),
                ('car_amfm', models.CharField(blank=True, max_length=100, null=True)),
                ('car_mssas', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_image', models.ImageField(blank=True, null=True, upload_to='media/carimage')),
                ('image_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rental.car')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mark_image', models.ImageField(blank=True, null=True, upload_to='media/mark')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='car',
            name='car_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rental.mark'),
        ),
    ]
