# Generated by Django 3.2.9 on 2021-12-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0004_rename_car_transmiossion_car_car_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_mssas',
        ),
    ]
