# Generated by Django 3.2.9 on 2021-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0005_remove_car_car_mssas'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_rating',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
