# Generated by Django 3.2.9 on 2021-12-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0006_car_car_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookNow_id', models.AutoField(primary_key=True, serialize=False)),
                ('BookNow_pick', models.CharField(blank=True, choices=[('Headquarter', 'Headquarter'), ('Tirana International Airport', 'Tirana International Airport')], default='Tirana International Airport', max_length=40, null=True)),
                ('BookNow_dropoff', models.CharField(blank=True, choices=[('Headquarter', 'Headquarter'), ('Tirana International Airport', 'Tirana International Airport')], default='Tirana International Airport', max_length=40, null=True)),
                ('BookNow_datep', models.DateField(blank=True, null=True)),
                ('BookNow_dated', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
