# Generated by Django 3.2.9 on 2021-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0007_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookNow_dated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookNow_datep',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
