# Generated by Django 3.2.9 on 2021-12-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0009_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
