# Generated by Django 3.2.9 on 2021-12-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0011_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
