# Generated by Django 3.2.9 on 2021-12-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0012_auto_20211211_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookNow_dropoff',
            field=models.CharField(blank=True, choices=[('Headquarter', 'Headquarter'), ('Tirana International Airport', 'Tirana International Airport')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookNow_pick',
            field=models.CharField(blank=True, default='HEADQUARTER', max_length=40, null=True),
        ),
    ]
