# Generated by Django 3.2.9 on 2021-12-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0013_auto_20211214_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookNow_dropoff',
            field=models.CharField(blank=True, default='TIRANA INTERNATION AIRPORT', max_length=40, null=True),
        ),
    ]
