# Generated by Django 3.2.9 on 2021-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental', '0014_alter_book_booknow_dropoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/mark'),
        ),
    ]
