# Generated by Django 3.2.9 on 2021-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_logo', models.ImageField(blank=True, null=True, upload_to='media/mark')),
                ('mark_image', models.ImageField(blank=True, null=True, upload_to='media/mark')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
