# Generated by Django 3.2.9 on 2021-12-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211216_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
